# Generated by Django 5.2 on 2025-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='context',
            field=models.TextField(blank=True, default=''),
        ),
    ]
