# Generated by Django 5.2 on 2025-06-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trash', 'Trash')], default='active', max_length=10),
        ),
    ]
