# Generated by Django 5.2 on 2025-06-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aiconversation_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconversation',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.material'),
        ),
    ]
