# Generated by Django 5.2 on 2025-06-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aiconversation_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(default=1, help_text='The user who owns this conversation', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
