# Generated by Django 5.2 on 2025-06-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aiconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, help_text='(Optional) A short description of this file.'),
        ),
    ]
