# Generated by Django 5.2 on 2025-06-04 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streak',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
