# Generated by Django 5.2 on 2025-06-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_streak_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
