# Generated by Django 5.2 on 2025-06-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_streak_longest_streak_streak_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='user',
        ),
        migrations.AddField(
            model_name='streak',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
